# Generated by Django 3.0.4 on 2020-03-31 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_id', models.BigIntegerField(default=0, verbose_name='広告主id')),
                ('master', models.CharField(blank=True, max_length=255, null=True, verbose_name='広告主')),
                ('nice', models.CharField(blank=True, max_length=255, null=True, verbose_name='いいね!')),
            ],
            options={
                'db_table': 'fb_base',
            },
        ),
        migrations.CreateModel(
            name='FacebookSearch',
            fields=[
                ('master_id', models.BigIntegerField(default=0, primary_key=True, serialize=False, verbose_name='広告主id')),
            ],
            options={
                'db_table': '広告主idリスト',
            },
        ),
        migrations.CreateModel(
            name='DetailInfo',
            fields=[
                ('detail_id', models.BigIntegerField(default=0, verbose_name='広告主id')),
                ('ad_id', models.BigIntegerField(default=0, primary_key=True, serialize=False, verbose_name='広告id')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='広告者名')),
                ('main_text', models.CharField(blank=True, max_length=255, null=True, verbose_name='メインテキスト')),
                ('sub_text', models.CharField(blank=True, max_length=255, null=True, verbose_name='サブテキスト')),
                ('sample_img', models.URLField(blank=True, max_length=255, null=True, verbose_name='画像リンク')),
                ('register_date', models.DateTimeField(auto_now_add=True, verbose_name='データベース登録日')),
                ('advertise_register', models.DateTimeField(blank=True, null=True, verbose_name='広告登録日')),
                ('latest_update', models.DateTimeField(auto_now=True, verbose_name='更新日')),
                ('memo', models.TextField(blank=True, max_length=300, null=True, verbose_name='memo')),
                ('connect', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_folder.BaseInfo')),
            ],
            options={
                'db_table': 'fb_detail',
            },
        ),
        migrations.AddField(
            model_name='baseinfo',
            name='key',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_folder.FacebookSearch'),
        ),
    ]
